### ISSUE TITLE
/usr/lib/libcurl.so.4: no version information available

### ISSUE THREAD

**Issue by lpvm** [nanopool/Claymore-Dual-Miner#116]
Hi,

I'm trying to run this in Void Linux, kernels 4.12 and 4.13.
Have an AMD RX 560 graphic card.

I have the following packages (marked with '*') refering to OpenCL installed.  The '-' are not installed.

```
[-] clinfo-2.2.17.06.14_1            Prints all information about OpenCL in the system
[*] libclc-git-20170816_1            Open implementation of the OpenCL C programming language
[-] luxmark-3.1_4                    OpenCL benchmark based on LuxCore
[*] mesa-opencl-17.2.2_1             Mesa implementation of OpenCL (r600+ only)
[*] ocl-icd-2.2.11_1                 Generic OpenCL ICD loader/demultiplexer
[-] ocl-icd-devel-2.2.11_1           Generic OpenCL ICD loader/demultiplexer - development files
[-] opencl-clhpp-2.0.10_1            OpenCL Host API C++ bindings (cl.hpp and cl2.hpp)
[-] opencl-headers-1.2.20160105_1    OpenCL (Open Computing Language) header files
[-] opencl2-headers-2.0.20160105_1   OpenCL 2.0 (Open Computing Language) header files
[*] catalyst-opencl-15.302_2         AMD catalyst driver 15.12 for Linux - OpenCL implementation
```

The problem is that there's some problem with `libcurl`.

```
$ ./start_only_eth.bash 
./start_only_eth.bash: line 6: $'\r': command not found
./ethdcrminer64: /usr/lib/libcurl.so.4: no version information available (required by ./ethdcrminer64)
(...)
ETH: 1 pool is specified
Main Ethereum pool is eth-eu1.nanopool.org:9999
No AMD cards in the list.
No NVIDIA CUDA GPUs detected.
No AMD OPENCL or NVIDIA CUDA GPUs found, exit
```

I've searched and the solutions seem to point to an alternative curl installation. I don't have any in `/usr/local`, but I have a 32 bit version installed in `/usr/lib32`.

```
# ls -l /usr/lib/libcurl*
-rw-r--r-- 1 root root 1030450 out  5 08:22 /usr/lib/libcurl.a
lrwxrwxrwx 1 root root      16 out  5 08:22 /usr/lib/libcurl.so -> libcurl.so.4.5.0
lrwxrwxrwx 1 root root      16 out  5 08:22 /usr/lib/libcurl.so.4 -> libcurl.so.4.5.0
-rwxr-xr-x 1 root root  506112 out  5 08:22 /usr/lib/libcurl.so.4.5.0
```

and:

```
# ls -l /usr/lib32/libcurl.*
-rw-r--r-- 1 root root 878160 out  5 08:50 /usr/lib32/libcurl.a
lrwxrwxrwx 1 root root     16 out  5 08:50 /usr/lib32/libcurl.so -> libcurl.so.4.5.0
lrwxrwxrwx 1 root root     16 out  5 08:50 /usr/lib32/libcurl.so.4 -> libcurl.so.4.5.0
-rwxr-xr-x 1 root root 525828 out  5 08:50 /usr/lib32/libcurl.so.4.5.0
```

What's wrong and how can I solve this issue?

**Comment by MsJamie** [comment]
I don't use or have Void Linux installed but on ArchLinux I must use libcurl.so.3 which is in the libcurl-compat package in the AUR and
LD_PRELOAD=libcurl.so.3 in my bash script to start up Claymore

I haven't been able to get it to work with libcurl.so.4 either and it appears to be hardcoded in. Also I tried to do a quick search and have no idea where to pull that for Void sorry.

For packages I have

clinfo
ocl-icd
opencl-amd 17.30.465504-2
opencl-headers 2:2.2.20170516-1   May be required as well
opencl-mesa 17.2.2-0
opencl-amd 17.30.465504-2

Which works good. Also one ubuntu box with amdgpu-pro 17.30-458935 and the equivalent packages there. If you need to use LD_PRELOAD you will most likely need to run the script with sudo, I need to on mine.

You should install clinfo for testing and I recommend it to make sure the opencl is working correctly

Ubuntu w/o sudo. On arch it's not an issue. If you are not seeing your card in the clinfo output it's most likely due to missing drivers for your OS

```
clinfo |grep '^Number'  -A4
Number of platforms                               0
```

Ubuntu requires sudo, but you should see output like this, possibly more platforms if you have an APU or onboard video as well

```
sudo clinfo |grep '^Number'  -A4
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (2442.7)
  Platform Profile                                FULL_PROFILE
--
Number of devices                                 1
  Device Name                                     Ellesmere
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2442.7)
```

Hope that helps

Also noticed in the binary for Claymore 10

strings ethdcrminer64 |grep -i gcc
GCC: (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

That would explain a bit for the older curl/libcurl

**Comment by stone212** [comment]
@lpvm I didn't have this problem after upgrading to 11.8.  If you also don't you could close this issue.

**Comment by lpvm** [comment]
Thanks.
