### ISSUE TITLE
Dual mine ETH+XVG

### ISSUE THREAD

**Issue by wonderbit** [nanopool/Claymore-Dual-Miner#175]
Hello,

I'm interested in dual mining ETH + XVG… I suppose it should be possible, since you can mine XVG using the blake2s algorithm (same as Siacoin).

I have tried mining to an blake2s XVG pool with "-dcoin SC" but it rejected all my shares.

Any help would be greatly appreciated.

**Comment by jwb6658** [comment]
Where did you see the algorithm was Blake? I thought it was scrypt which would make it an asic algo.

**Comment by wonderbit** [comment]
It’s multi algorithm actually… scrypt, Groestl, Lyra2rev2, blake2s and X17

https://vergecurrency.com/pools/

**Comment by Th3F1n4nc3** [comment]
I am trying to do the same thing. I don't think Claymore supports blake2s atm. Siacoin's algo is blake2b.

**Comment by BenRacicot** [comment]
Have you guys found a way to do this?

**Comment by Th3F1n4nc3** [comment]
No not yet. I've tried contacting the devs for Claymore. No word yet.

On Jan 21, 2018 5:55 AM, "Ben Racicot" <notifications@github.com> wrote:

Have you guys found a way to do this?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nanopool/Claymore-Dual-Miner/issues/175#issuecomment-359250149>,
or mute the thread

**Comment by BenRacicot** [comment]
@Th3F1n4nc3 Man, dual mining ETH and x17 would be incredible!

**Comment by pascalandy** [comment]
+1

**Comment by EMO18** [comment]
Hi, you may have already discovered this but the latest Claymore v11 will support ETH+XVG - Mining XVG with Blake2s Algo

**Comment by wonderbit** [comment]
@EMO18 Yes, thanks for the heads-up
