### ISSUE TITLE
4 rig GPU rig rebooting z270f 1060 3gb 1070

### ISSUE THREAD

**Issue by fabiomagina** [nanopool/Claymore-Dual-Miner#74]
Hey guys, I'm with a serious problem. My rig is constantly rebooting. The max time up is 25min.
I already tried to install different drivers in win10 and win7. The best now is win7 during something like 25min up. 

GPU max temperature 75. GPU 50oC
2 gtx 1070
2gtx 1060 3gb
Rm1000i corsair 
Tried with 3 and 2 I just can't get stable with 2 1060 3g
1 1070 mini gigabyte and other 1070 schools
I'm running on intel g3930 and 4gb ram. May be a issue with memory? Already set 16gb virtual and.
Already 1 week trying to solve my last shot is install Ubuntu but I'm new to it

**Comment by Reubenwelsh** [comment]
Im guessing your not overclocking, if that that would be my first step troubleshooting.
If i understand you correctly, your getting stable connection when running 3 GPU's, is that 3 in any combination or do you mean that the problem is ONLY when you run 2x1060
have you tried both combinations with 2x1070 and 1x 1060 so make sure one of the cards dont have  a defect?

Are you seeing BSOD or other reboot errors, you can turn on debuglogging to help you find your root cause.

Here is a quick setup i use on my machines for ubuntu 16.04- Feel free to give it a try :)

wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1404_7.5-18_amd64.deb
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install git cmake libcryptopp-dev libleveldb-dev libjsoncpp-dev libjsonrpccpp-dev libboost-all-dev libgmp-dev libreadline-dev libcurl4-gnutls-dev ocl-icd-libopencl1 opencl-headers mesa-common-dev libmicrohttpd-dev build-essential cuda -y
git clone https://github.com/Genoil/cpp-ethereum/
cd cpp-ethereum/
mkdir build
cd build
cmake -DBUNDLE=cudaminer ..
make -j8
cd ethminer

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
./ethminer -G -F http://eth-eu.dwarfpool.com:80/0xc6717674907e5ae37d4f6ca27d35b9bb8ef1c74c/$HOSTNAME
